### ISSUE TITLE
[Plans]: Checklist for reimplementation + 2.1 features

### ISSUE THREAD

**Issue by Zepalesque** [Zepalesque/Aether-Redux-Issue-Tracker#127]
This is essentially the actual checklist for 2.1, the older one is more of a general ideas list (this one is more concrete)

Biomes:
- [x] Gilded Groves (substantial rework)
- [ ] Blight
- [ ] Skyfields
- [ ] Frosted Biomes
- [ ] Skyroot Shrublands
- [ ] Cloudcaps

Items:
- [x] Wynd Oats + associated items (panicle, bagels, pies)
- [ ] Enchanted Ring
- [ ] Ring of Wisdom (zanite instead of emerald)
- [ ] Sentry Ring
- [ ] Shroom Ring
- [ ] Ring of Construction (Valkyrie Ring)
- [ ] Vampire Amulet (new effect plus rework the way it does everything, maybe use vanilla cooldown or something)
- [ ] Cockatrice Feather + Feather of Warding
- [x] Airbound Cape (retexture?)
- [ ] Snailshell Shield
- [ ] Grand Victory Medal
- [ ] Solar Emblem
- [ ] Blightbunny Fang
- [ ] Maybe readd swet jelly?
- [x] (new) Refined Sentrite (should be used for things like the Ring of Wisdom and the Sentry Ring)
- [ ] Sentrite scraps? Maybe could be melted into a Refined Sentrite Chunk
- [ ] (new, maybe) Escargot from mykapods
- [ ] Raw ores

Blocks:
- [x] Sentrite
- [x] Sentrite Bricks
- [ ] Sentrite Pillar (?)
- [ ] Divinite (potentially rework so this *IS* angelic stone, and the existing block is ‘angelic stone tiles, maybe it could be named Angelstone)
- [ ] Polished Divinite/Angelstone
- [x] Mossy stones
- [x] Blightmoss
- [x] (New, maybe) Flutemoss/Aermoss
- [x] (New, maybe) Gildmoss
- [ ] Fungal Growth
- [ ] Lightroot (rework to be more like the old quickroots, could be neat to make these be able to be crafted into an item that can place infinite temporary light sources, though with a cooldown/refresh rate)
- [ ] Flowers

Note: this list is still incomplete
