### ISSUE TITLE
[PLANNED] 2.0 update checklist

### ISSUE THREAD

**Issue by Zepalesque** [Zepalesque/Aether-Redux-Issue-Tracker#48]
This is a checklist of planned features for v2.0, and will be updated as I finish things / find new ones.

General/Large scale changes:
- [x] Remove unnecessary built-in packs
- [x] Biome tints
- [x] Look over feature placement and distribution in *all* biomes, tweak it as necessary - seems to be reasonable
- [x] Consider a pre-release?
- [x] Trailer for update (release when update is out, but complete before)
- [x] Trailer description
- [x] When all else is done, backport to 1.19.2 for one final release (maybe bugfixes later as well, may also port v2.1 possibly)

Config:
- [x] Configuration option for Bronze Dungeon structure upgrades
- [x] Disable mining speed changes by default
- [x] Configuration option to disable Gilded/Golden vines
- [x] Config to disable the cloud layer datapack

Resources / Built-in Packs:
- [x] Remove many of the existing built-in packs, they can be moved to the Reforged II resource pack
- [x] Consider moving mob sound changes to built-in packs
- [x] Modify classic cockatrices pack, so that_instead_ there is a 'purple cockatrices' or 'blighted cockatrices' pack that is enabled by default (should also affect the default model cockatrices)
- [x] Alter Aechor Plant design
- [x] Veridium pack variants for veridium dart shooter
- [x] Update Jappified pack, add new rings

Reworks:
- [x] Rework Subzero Crossbow, new particles, splash effect?
- [x] Phoenix Ring -> Phoenix Emblem
- [x] Valkyrie Ring -> Grand Victory Medal (gives health regen that scales as health decreases, along with removing the need to collect more medals for every valk queen fight)
- [x] Enchanted ring should be a base to craft other ring accessories
- [x] Sentry Ring rework - will be a variant of the enchanted ring; hitting enemies while wearing will cause electric embers to spark off of them, damaging other mobs they hit and creating nice spark particles
- [x] Change the method of obtaining the Slider Music disc

Additions:
- [x] Airbound Cape (replaces previous sentry ring, gives double jump)
- [x] Raw Gravitite
- [x] Raw Gravitite Block
- [x] Gravitite Ingot (implement fully in future update)
- [x] Ring of Wisdom (grants additional xp drops)
- [x] Shroom ring (Gives an adrenaline ability)
- [x] Veridium arrows (more damage and more accuracy than normal arrows
- [x] Nerf veridium arrow damage and make them a tiny bit faster if possible
- [x] Replace Veridium Arrows with Veridium Dart Shooters
- [x] Redux Menu screen
- [ ] (MAYBE, may save for a future update) implement a Paradise Lost-like swet behavior

Tweaks:
- [x] Increase number of maximum layers in leaf piles, allow stacking of leaf piles on top of eachother
- [x] Add biome colors for aether biomes that match their climates
- [x] Add the same but for aether grass in vanilla biomes
- [x] Increase spawnrate of veridium
- [x] Make golden clover item use top texture
- [x] Holysilt + Aether dirt to make Coarse Aether Dirt
- [x] Potentially rename Aether Grass’s id from `aether_short_grass` to `short_aether_grass`
- [x] Suffix for Redux advancements
- [x] Jade overrides to indicate things like mob model changes
- [x] Change grass patch feature to not place on coarse dirt
- [x] Improve Gravitite Ingot texture
- [x] Fully implement Gravitite Ingot config (config enables datapack, maybe adds lore overrides? Not sure)
- [x] Improve Veridium Ore texture (make it fit better with the base mod holystone)
- [x] Nerf Veridium sword
- [x] Further nerf the snailshell shield
- [x] Decrease size of mossy holystone and aerogel blobs
- [x] Redo menu panorama
- [x] Rename Phoenix emblem to Solar Emblem
- [x] `- Modified by the Aether: Redux -` suffix for the gravitite advancement when the ingot config is enabled
- [x] Fix Infused dart shooter chute (shoot?) pallete
- [x] Raw Gravitite blocks should not use the rare color
- [x] Alter Cloudcap spawnrate
- [x] Switch Solar Emblem to use vanilla item cooldown system

Code refactors:
- [x] Use mixins rather than renderer overrides for mob model changes
- [x] Remove biome placement patches, as the new biome tints along with block-below-predicate patches render them completely useless
- [x] Fade effect for fallen leaves rather than instantaneous disappearance
- [x] Redo vanilla block tint system for the aether

Things to investigate:
- [x] Figure out how to use biome modifiers to add a grass color variable seperate from vanilla’s
- [x] Mixin to make mobs avoid quicksoil? But this time for `QuicksoilBlock` itself to prevent compat issues
- [x] Potentially mixin to fix a neoforge bug related to biome modifiers and grass color, also report to neoforge issue tracker (mixin bc they’re unlikely to fix it for 1.20.1)

Removals:
- [x] Remove Bundle of Aether Grass
- [x] Remove oat muffins ):
- [x] Remove depth parameter from the blight / cloudcaps
- [x] Remove Double Cloudcap plants
- [x] Remove Quickroots

Fixes:
- [x] Fix weird behavior from the `getCandidatePacks` method in the `ReduxOverridesPackResources` class
- [x] Fix incorrect buff of uninfused veridium sword rather than infused one
- [x] Make Zanberry bushes spawn properly
- [x] Log error for dark swet loot modifier

Wyndsprouts and other sprouts rework:
- [x] Remove Oats
- [x] Remove Luxbuds and their purified variant
- [x] Move Luxbud advancement to cockatrice feather
- [x] Add bundles of wyndsprouts
- [x] Wyndsprout seeds
- [x] Wyndsprout Bagel (may alter name in future)
- [x] Other variants of the bagel, like blueberry (could also mix the three sprout seeds with it for an everything bagel lol)
- [x] Oatmeal
- [x] Wyndsprout Crop

Gilded Groves rework:
- [x] Remove Aevyrn Bushes
- [x] Add config to switch between normal/enchanted grass
- [x] Implement enchanted blockstates for plants in the biome (or for white flowers, implement a seperate block)
- [x] Make Golden Oaks more common than Gilded ones
- [x] Secondary, potentially more open biome variant, maybe with more Gilded trees and no stone ‘cracks’ on ground (Gilded Grasslands?)
- [x] Consider bringing back the Zyatrix for the grasslands
- [x] Config to use skyroot-like gilded oak shapes

Blight rework:
- [x] Remove Blighted Fungi
- [x] Implement Corrupted Vines
- [x] Try to make cockatrices spawn here at daytime
- [x] Blightbunny
- [x] Blightbunny tooth
- [x] Spear of the Blight
- [x] Increase chance to blight mobs when hit with a *thrown* spear of the blight
- [x] Make the spear enchantable
- [x] Inebriation Potion from Blighted spores (Potion of Intoxication?)
- [x] Redo Blightwillow Tree shape
- [x] Give blightwillows more height variation
- [x] Feather of Endurance accessory
- [x] Make Blighted Caves even rarer outside the blight, perhaps more common in it
- [x] Blightwillow Leaf Piles
- [x] Blighted Aerclouds (will heal blight mobs such as cockatrices and blightbunnies and will harm others)

Highfields (Skyfields) rework:
- [x] Remove Chromatic Bushes (More specifically, rename them, retexture them, and move them to the unnamed Shrublands biome)
- [x] Increase chance of spawning Skyroot trees
- [x] Remove Firecaps
- [x] Add white/purple flowers
- [x] Implement Xaelia flowers
- [x] Fix Xaelia worldgen
- [x] Crystal tree spawns?
- [x] Rename to skyfields
- [x] Rename fieldsprout to fieldsproot
- [x] Fix missing item model stuff for fieldsproot leaves and fieldsproot petals
- [x] Fix language name thing for fieldsproot leaves 

Cloudcaps rework:
- [x] Redo mushroom shape
- [x] Redesign Springshrooms
- [x] Implement Shimmerstools
- [x] Spore particles from Cloudcap Spores
- [x] Large patches of coarse dirt
- [x] Springshroom Jelly block
- [x] Retexture Avelium
- [x] Maybe turn Lightroots into a vine-like block similar to glow lichen?
- [x] Rocks
- [x] Implement Shimmercow
- [x] Fungal Caves
- [x] Consider using randomized textures for cloudcap cap blocks
- [x] Mykapod (funny mushroom snail thing)
- [x] Mykapod Shell chunk
- [x] Snailshell Shield (cancels knockback, may nerf to a ~75% or so knockback resistance)
- [x] Shell Shingles block (blast-resistant, placeable by dispensers, breakable by pistons, enchantable into hardened variant which does not have the dispenser and piston behavior, maybe has some alternative behavior)
- [x] Mykapod sounds
- [x] Figure out what on *earth* is happening with the mykapod shedding animation???
- [x] Related - Figure out why mykapod animation is wonky when pausing the game
- [x] Make mykapods spawn in the biome properly
- [x] Make lightroots spawn on avelium
- [x] Make shimmercow have glowing back mushrooms (use entity emissive translucent rendertype)

Frosted Forests rework:
- [x] Add snow layers
- [x] Purple variant of Glacia trees
- [x] Two sub-biomes, frosted tundra and glacial taiga
- [x] Aerogel patches in stone?
- [x] Increased spawnrate of Icestone
- [x] Remove Frosted Holystone
- [x] Rework Frosted Fern texture
- [x] Snow side texture for glacia leaves
- [x] Decrease density of trees in frosted tundra

New biome: Skyroot Shrublands:
- [x] Rename Chromaberries, give them a new dark green bush/shrub to grow on
- [x] Implement biome
- [x] Trees (less dense than other biomes)
- [x] Bushes
- [x] Rework Frosted Ferns to no longer be just cold biome plants and put them here
- [x] _**Slightly**_ more tan/yellowish grass color
- [x] Genesis pine shaped trees
- [x] Denser grass
- [x] Denser bushes
- [x] Coarse dirt patches

Mod Compatibility:
- [x] Aether: Genesis falling leaves
- [x] Bring changes from base mod biomes to Genesis vibrant biomes
- [x] Galosphere Glow/Spectral flare support for Subzero Crossbow
- [x] Make Coarse Aether Dirt interchangeable with Deep Aether’s Aether Coarse Dirt
- [x] Ancient Aether grass compatibility
- [x] Deep Aether plant tints
- [x] Ancient Aether plant tints
- [x] Investigate gravitation for compat features
- [x] Ancient Aether Sky grass feature compat
- [x] Ancient Aether falling leaves

Other things to do:
- [x] Update screenshots on all three mod pages (curseforge, modrinth, planetminecraft)
- [x] Redo mod description
- [ ] Update GitHub description
- [ ] Finish GitHub credits section

**Comment by Zepalesque** [comment]
Hmm, I should probably convert this to a github project
Edit: nah

**Comment by Zepalesque** [comment]
aaaaaaaaaaaaaa this update is going to take _forever_

![thanos-snap-emoji](https://media1.tenor.com/m/Rcl4uRH7FIkAAAAC/thanos-snap-emoji.gif)

**Comment by Zepalesque** [comment]
hmm, I think I’m going to split this into three seperate issues:
2.0 features, 2.1 plans and future plans
That way I’m not tracking things I need to do for _this_ update in the same place as future features

**Comment by Od1nB** [comment]
Hey 😄 , when are you planning next release so that #52 will be included?

**Comment by Zepalesque** [comment]
Likely in the near future, the update isn’t quite done yet but I’d like to get it finished *relatively* soon

**Comment by Zepalesque** [comment]
pre-release is out!
https://github.com/Zepalesque/The-Aether-Redux/releases

**Comment by Zepalesque** [comment]
IT’S _DOOOOOOOONE!!!_
